<?php
 
                /***************************************************************************
		                                extension.php
		                             -------------------
		    begin                : 2003 September 29 Sunday
		    copyright            : (C) 2003 The nm114.net Group
		    email                : brgd@nm114.net
		
		    $Id: extension.php,v 0.1 2003-9-29 12:47  brgd $
		
		 ***************************************************************************/

$nmxhwEx = 'php';
$nmxhwTfEx = '.htm';

?>